### ISSUE TITLE
Japanese translation is wrong

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/windows-driver-docs.ja-jp#35]
- Wrong:
-----
Windows 10 に対する申請をテストする場合は Hardware Lab Kit (HCK) を使い、Windows 10 より古いバージョンの Windows に対してテストする場合はハードウェア認定キット (HLK) を使います。
-----

- Correct:
-----
Windows 10 に対する申請をテストする場合は Hardware Lab Kit (HLK) を使い、Windows 10 より古いバージョンの Windows に対してテストする場合は Hardware Certification Kit (HCK) を使います。
-----

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b8daa508-0b31-6850-8053-77882e924180
* Version Independent ID: d9a5549b-39ea-1ba2-483b-0a202dd1639c
* Content: [複数の Windows バージョンで Microsoft によって署名されたドライバーを取得する - Windows drivers](https://docs.microsoft.com/ja-jp/windows-hardware/drivers/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md](https://github.com/MicrosoftDocs/windows-driver-docs.ja-jp/blob/live/windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by srvbpigh** [comment]
Hello, @damochiz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
こんにちは、@damochiz

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/windows-hardware/drivers/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
