### ISSUE TITLE
日本語翻訳し過ぎの間違い

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/windows-driver-docs.ja-jp#37]
とても見にくい。それぞれ次の様に修正されるべきです。

状態_SUCCESS を比較することです。 →STATUS_SUCCESS を比較することです。
NT_成功 (状態) →NT_SUCCESS(Status)
NT_情報 (状態) →NT_INFORMATION(Status)
NT_警告 (状態) →NT_WARNING(Status)
NT_エラー (状態) →NT_ERROR(Status)
SUCCESS_(エラーがないことを示す) 状態を返した場合 →エラーがないことを示す STATUS_SUCCESS
ステータスステータス_オブジェクト_名前_存在する →STATUS_OBJECT_NAME_EXISTS
ステータス_バッファー_(エラーコード) がが小さい_ →STATUS_BUFFER_TOO_SMALL
ステータス_バッファー_オーバーフロー (警告コード) →STATUS_BUFFER_OVERFLOW(警告) 
NT_SUCCESS または NT_エラーを使用して →NT_SUCCESS または NT_ERROR を使用して

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9acefe2e-2d94-4a68-d86d-d6c88fb2cbf6
* Version Independent ID: 4bbb38d6-c521-e9bc-28a1-f527f4a112bb
* Content: [NTSTATUS 値の使用 - Windows drivers](https://docs.microsoft.com/ja-jp/windows-hardware/drivers/kernel/using-ntstatus-values#feedback)
* Content Source: [windows-driver-docs-pr/kernel/using-ntstatus-values.md](https://github.com/MicrosoftDocs/windows-driver-docs.ja-jp/blob/live/windows-driver-docs-pr/kernel/using-ntstatus-values.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by srvbpigh** [comment]
Hello, @ahidaka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@ahidaka  様: 

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 

サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム
