### ISSUE TITLE
翻訳訂正

### ISSUE THREAD

**Issue by scrips** [MicrosoftDocs/windows-driver-docs.ja-jp#38]
FLTFL_FILTER_UNLOAD_MANDATORY が日本語訳されてしまっています
---
FilterUnloadCallback ルーチンには 1 つの入力パラメーターがあります。 Flags は NULL または FLTFL_FILTER_UNLOAD_MANDATORY が指定できます。 フィルターマネージャーは、アンロード操作が必須であることを示すために、このパラメーターを FLTFL_FILTER_UNLOAD_MANDATORY に設定します。 このパラメーターの詳細については、「 PFLT_FILTER_UNLOAD_CALLBACK」を参照してください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5ff3468a-d7a7-40a0-0a49-5430765456e6
* Version Independent ID: de75e9ad-53a3-ef0d-c8e0-f097161b600f
* Content: [FilterUnloadCallback ルーチンを記述する - Windows drivers](https://docs.microsoft.com/ja-jp/windows-hardware/drivers/ifs/writing-a-filterunloadcallback-routine#feedback)
* Content Source: [windows-driver-docs-pr/ifs/writing-a-filterunloadcallback-routine.md](https://github.com/MicrosoftDocs/windows-driver-docs.ja-jp/blob/live/windows-driver-docs-pr/ifs/writing-a-filterunloadcallback-routine.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by srvbpigh** [comment]
Hello, @scrips
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@scrips 様:

投稿いただき、ありがとうございます。

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。

サポートいただきありがとうございます。

Microsoft DOCS グローバル エクスペリエンス チーム
