### ISSUE TITLE
The link to WDK insider preview download of Japanese version page is incorrect.

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/windows-driver-docs.ja-jp#39]
At the link of the Japanese page
https://docs.microsoft.com/ja-jp/windows-hardware/drivers/download-the-wdk

Section of  "Related downloads", 
link of "Download the WDK Insider Preview" indicates
https://www.microsoft.com/ja-jp/software-download/windowsinsiderpreviewWDK
but its is missing.

This link should be followings.
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewWDK

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Windows Driver Kit (WDK) のダウンロード - Windows drivers](https://docs.microsoft.com/ja-jp/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs.ja-jp/blob/live/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by srvbpigh** [comment]
Hello, @ahidaka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ahidaka

Thank you for your feedback.
I cannot reproduce the error. The link you mention leads me to the en-US page
@nokura can you please check this issue?

Kind regards,
Microsoft DOCS International Team

**Comment by ahidaka** [comment]
Thanks, I confirmed that the link of https://docs.microsoft.com/ja-jp/windows-hardware/drivers/download-the-wdk was fixed.
